
CREATE TABLE [Patient]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Name] VARCHAR(180) NOT NULL,
	[Phone] VARCHAR(14) NOT NULL,
    [PhotoPath] VARCHAR(180) NULL,
    [DateOfBirth] DATE NOT NULL,
    [CreateDate] DATETIME NOT NULL DEFAULT(GETDATE()),
)

CREATE TABLE [Exam]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    [IdPatient] UNIQUEIDENTIFIER NOT NULL,
	[Type] INT NOT NULL DEFAULT(1),
	[Date] DATETIME NOT NULL DEFAULT(GETDATE()),
    [Channel] INT NOT NULL,
	[Duration] TIME(7) NULL,
	[Frequency] INT NULL,
    FOREIGN KEY ([IdPatient]) REFERENCES [Patient]([Id])
)

CREATE TABLE [BitalinoFrame]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    [IdExam] UNIQUEIDENTIFIER NOT NULL,
	[Identifier] VARCHAR(20) NOT NULL,
    [Seq] INT NOT NULL,
    [A0] INT NOT NULL,
    [A1] INT NOT NULL,
    [A2] INT NOT NULL,
    [A3] INT NOT NULL,
    [A4] INT NOT NULL,
    [A5] INT NOT NULL,
    [D0] INT NOT NULL,
    [D1] INT NOT NULL,
    [D2] INT NOT NULL,
    [D3] INT NOT NULL,
    [CreateDate] DATETIME NOT NULL DEFAULT(GETDATE()),
    FOREIGN KEY ([IdExam]) REFERENCES [Exam]([Id])
)